# Generated by Django 5.0 on 2023-12-11 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50, verbose_name='Skill Name')),
                ('description', models.TextField()),
                ('experience_level', models.CharField(choices=[('L', 'Learning'), ('P', 'Practicing'), ('E', 'Expert'), ('M', 'Master')], default='M', max_length=50)),
                ('skill_type', models.CharField(default='Tech', max_length=50, verbose_name=[('Tech', 'Technical'), ('Prod', 'Product'), ('Sales', 'Sales'), ('Market', 'Marketing'), ('Managerial', 'Managerial')])),
            ],
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=50, verbose_name='Employer Name')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('achievements', models.TextField()),
                ('related_skills', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mainResume.skill')),
            ],
        ),
    ]
