# Generated by Django 5.0 on 2023-12-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainResume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
