# Generated by Django 5.0 on 2023-12-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainResume', '0002_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('Tech', 'Technical'), ('Prod', 'Product'), ('Sales', 'Sales'), ('Market', 'Marketing'), ('Managerial', 'Managerial')], default='Tech', max_length=50),
        ),
    ]
