# Generated by Django 5.0 on 2023-12-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainResume', '0003_alter_skill_skill_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='end_date',
        ),
    ]
