# Generated by Django 5.0 on 2023-12-11 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainResume', '0004_remove_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
