# Generated by Django 5.0 on 2023-12-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainResume', '0005_experience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='position_name',
            field=models.CharField(default='Product Manager', max_length=50, verbose_name='Position Name'),
            preserve_default=False,
        ),
    ]
