# Generated by Django 5.0 on 2023-12-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainResume', '0006_experience_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company_url',
            field=models.CharField(blank=True, max_length=50, verbose_name='Employer URL'),
        ),
    ]
